### ISSUE TITLE
Incorrect behaviour of the algorithm responsible for filling the polygon (EditableGeoJsonLayer)

### ISSUE THREAD

**Issue by stuymedova** [visgl/deck.gl-community#103]
**Reproduction steps:**
- Draw out a polygon in the DrawPolygonMode
- Switch to the ModifyMode
- Modify the polygon such that the edges overlap forming an hourglass

**Expected behaviour:**
- The two triangles of the hourglass are filled

**Actual behaviour:**
- The filling is lacking an edge

<img width="522" alt="image" src="https://github.com/visgl/deck.gl-community/assets/53351370/f8868de0-9942-450a-aafa-292288f52df5">

**Comment by donmccurdy** [comment]
I believe deck.gl expects that the defined curve has a consistent _“winding order”_, you'll see a similar result on https://geojson.io/ and https://play.placemark.io/. Rendering relies on concepts like the [nonzero rule](https://en.wikipedia.org/wiki/Nonzero-rule) and [back-face culling](https://en.wikipedia.org/wiki/Back-face_culling). 

If you were to load these points...

```
D    A

B    C
```

... in a 3D viewport and view from all sides, I think you'd see the renderer draws two triangles, ABC and CDA, with ABC facing up and CDA facing down. If you want to draw both sides of all triangles, you can [disable back-face culling](https://github.com/visgl/deck.gl/discussions/6958#discussioncomment-2835637), but the result will still be a bit different from the hourglass you describe. For that I think you would need a more opinionated interpretation of the polygon.

**Comment by felixpalmer** [comment]
Agree with @donmccurdy, this is expected behavior. Imagine you had a fence surrounding a house, painted white only on the side enclosing the house. The side defines the "inside" of the shape. If you drag the fence to make an hourglass, the white side is no longer enclosed, and thus the fence no longer encloses an area, in other words it is not a valid polygon.

If you need to draw an hourglass, you need to trace both polygons with the same winding order

**Comment by stuymedova** [comment]
We're using the popular [turf.js](https://github.com/Turfjs/turf) library to filter data points so that only the ones within the polygon are included, and we get an (here expected) hourglass behaviour there. Is it possible to configure or swap out from the outside the algorithm responsible for the calculation?

**Comment by stuymedova** [comment]
Or, alternatively, there is a setting called preventOverlappingLines. It would be great to enforce this behaviour when the user is editing the polygon as well. For instance, when the user lifts up the mouse key we could check for the overlap, and if so, a vertex could go back to where it was before the user started dragging.
