### ISSUE TITLE
deck.gl-community/react npm package

### ISSUE THREAD

**Issue by rsbh** [visgl/deck.gl-community#104]
Hey,
We are using the `@nebula.gl/overlays` package in our project. Due to that, we are unable to upgrade other packages as it has a peer dependency of `react@' 0.14. x—16.x `. As it has been forked as `deck.gl-community/react`, I was trying to use that. But I was unable to find the package anywhere. Can you tell me the timeline to publish that to any public registry?

**Comment by ibgreen** [comment]
https://www.npmjs.com/package/@deck.gl-community/editable-layers

**Comment by ibgreen** [comment]
Please use discussions unless you are reporting a bug
