### ISSUE TITLE
Use geosjon package instead of redefining geojson types

### ISSUE THREAD

**Issue by abouroubi** [visgl/deck.gl-community#107]
In deck.gl v9 they are using the package 'geojson' for type definitions of GeoJSON objects.
But the 'editable-layer' is using a custom type definitions from this file: https://github.com/visgl/deck.gl-community/blob/a2452cac792b4e0256facf6e6595d082d252d698/modules/editable-layers/src/utils/geojson-types.ts

Maybe it's a better idea to use the same package as deck.gl to avoid types mismatch.

**Comment by ibgreen** [comment]
For book keeping purposes, we like keep the github "issues" for confirmed bugs or tasks and use the discussions tab for questions and proposals.

. In fact there is already a discussion around this topic https://github.com/visgl/deck.gl-community/discussions/106
