### ISSUE TITLE
Audit/Review/verify names of modules/packages

### ISSUE THREAD

**Issue by dylans** [visgl/deck.gl-community#11]
Determine best names for what are current graph-gl and react-graph-gl, maybe it should be something to reflect a core, layers, and the react component?

**Comment by dylans** [comment]
Thinking about this more, there's really not much in graph-gl if we split the layers out. I'm inclined to leave them in for now for simplicity, or at least until we get other cleanup done first and perhaps a migration to TS.

So for now I would leave them as graph-gl and react-graph-gl.

**Comment by ibgreen** [comment]
to be honest I wasn't suggesting that we split graph-gl. 

I was just suggesting that we rename the entire module to `graph-layers`. 

If as you say there is not much else going on, then that sounds reasonable. A layer module can export a few utilities.

**Comment by dylans** [comment]
Resolved in 91fae5a471915efcff3180956e66142f2f94b213
