### ISSUE TITLE
pickingLineWidthExtraPixels doesn't work with lineStrings

### ISSUE THREAD

**Issue by sgullen-hypergiant** [visgl/deck.gl-community#111]
It seems like pickingLineWidthExtraPixels param is only working on polygon features, not lineStrings. This is pretty annoying to deal with. Anyone have any suggestions for how to resolve this? Filter out the lines, duplicate, and add sublayer is the only thing I could come up with and I'm not even sure it'll work right.

**Comment by ibgreen** [comment]
@sgullen-hypergiant  There repo is a collection of different frameworks and components, so unfortunately it is not immediately clear to me what part of the code we are talking about, you'd need to add some information about that.

Also for issue discipline reasons, I will ask that we keep questions in the discussions tab until we are reporting a confirmed issue.
