### ISSUE TITLE
Module editable-layers has implicit dependency to layers

### ISSUE THREAD

**Issue by cg-sat** [visgl/deck.gl-community#112]
The module editable-layers has no explicit dependency to module layers: https://github.com/visgl/deck.gl-community/blob/master/modules/editable-layers/package.json

In fact the segments-layer is importing the layers module: https://github.com/visgl/deck.gl-community/blob/646f8328d27d67d596f05c9154072051ec5cf4f0/modules/editable-layers/src/lib/layers/segments-layer.ts#L9

This causes a build failure for any project, that only imports `@deck.gl-community/editable-layers`, but not `@deck.gl-community/layers`. The workaround is to also import `@deck.gl-community/layers`, but this implicit dependency should be made explicit by defining layers as peerDepdendency for editable-layers.

**Comment by ibgreen** [comment]
>  this implicit dependency should be made explicit by defining layers as peerDepdendency for editable-layers.

@cg-sat Thanks for reporting. Yes, that sounds reasonable. I believe a peerDependency would follow the conventions in deck.gl etc. 

Are you able to put up a PR to help speed things up?

**Comment by cg-sat** [comment]
@ibgreen I cloned the repo and made the necessary changes in package.json of editable-layers module. While testing the correct package resolving, npm uncovered issue #114

**Comment by ibgreen** [comment]
Landed, pending #126
