### ISSUE TITLE
Publish first version to npm

### ISSUE THREAD

**Issue by dylans** [visgl/deck.gl-community#12]
Blocked on #10 #11 and setting up the npm org.

**Comment by donmccurdy** [comment]
It looks like the graph layer packages are on npm now – should this issue be closed? Or does it refer to doing a new publish from this repository? Thanks!

**Comment by ibgreen** [comment]
I think @dylans is able to consume these from npm now. We may of course want to continue to consider what the best module naming scheme is for publishing modules from this repo, but we can close this issue.
