### ISSUE TITLE
How do I run examples

### ISSUE THREAD

**Issue by atulpatare** [visgl/deck.gl-community#15]
Im not able to run the examples. Steps I performed

```
git clone <repo>
npm i
npm run build # build works
```

I am not able to run the tests, getting below error

```
TSError: ⨯ Unable to compile TypeScript:
error TS6046: Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'es2020', 'es2022', 'esnext', 'node12', 'nodenext'.
```

I am using 
node `v18.16.1` and tried with `v16`

If you can you update the Readme or add steps to run different modules, examples and the website that will be great. Thanks

For testing the graph layer, I just copied required jsx files into my project and tested it out.

**Comment by donmccurdy** [comment]
Work in progress:

- https://github.com/visgl/deck.gl-community/pull/31

**Comment by donmccurdy** [comment]
Adding documentation for running examples in:

- https://github.com/visgl/deck.gl-community/pull/47
